version: "3.8"

services:
  app:
    image: 10.10.0.3:5000/auth-service-front:1.0.0
    environment:
      AUTH_API_URL: https://api.auth.chauffagistes-btc.fr
      BASE_URL: https://auth.chauffagistes-btc.fr
      HOSTNAME: "0.0.0.0"
    networks:
      - chauffagistes-net
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.chauffagistes.host == itrider
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth-service-front.rule=Host(`auth.chauffagistes-btc.fr`)"
        - "traefik.http.routers.auth-service-front.entrypoints=websecure"
        - "traefik.http.routers.auth-service-front.tls.certresolver=letsencrypt"
        - "traefik.http.services.auth-service-front.loadbalancer.server.port=3000"

networks:
  chauffagistes-net:
    external: true
  traefik-public:
    external: true