services:
  app:
    image: 10.10.0.3:5000/heatboard:1.1.5
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      DB_HOST: pg-ha-prod_haproxy
      DB_USER: heatboard
      DB_NAME: heatboard
      DISCORD_CLIENT_ID: "1100450456091766907"
      DISCORD_REDIRECT_URI: https://heatboard.chauffagistes-btc.fr/api/auth/discord/callback
      NEXTAUTH_URL: https://heatboard.chauffagistes-btc.fr
      COOKIE_DOMAIN: .chauffagistes-btc.fr
      BASE_URL: https://heatboard.chauffagistes-btc.fr
      API_URL: https://chauffagistes-pool.fr:3000
      HISTORY_API_URL: https://history.chauffagistes-btc.fr
      BITCOIN_API_URL: https://bitcoin.chauffagistes-btc.fr
      AUTH_URL: https://auth.chauffagistes-btc.fr
      AUTH_API_URL: https://api.auth.chauffagistes-btc.fr
    secrets:
      - source: heatboard_prod_db_password
        target: heatboard_db_password
      - source: heatboard_prod_pool_token
        target: heatboard_pool_token
      - source: heatboard_prod_session_password
        target: heatboard_session_password
      - source: discord_client_secret_prod
        target: heatboard_discord_client_secret
      - source: heatboard_prod_nextauth_secret
        target: heatboard_nextauth_secret
    networks:
      - chauffagistes-net
      - traefik-public
      - pg-prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.worload == true
      update_config:
        order: start-first
        monitor: 60s
        failure_action: rollback
      rollback_config:
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.heatboard.rule=Host(`heatboard.chauffagistes-btc.fr`)"
        - "traefik.http.routers.heatboard.entrypoints=websecure"
        - "traefik.http.routers.heatboard.tls.certresolver=letsencrypt"
        - "traefik.http.services.heatboard.loadbalancer.server.port=3000"

volumes:
  heatboard-db-data:

networks:
  chauffagistes-net:
    external: true
  traefik-public:
    external: true
  pg-prod:
    external: true

secrets:
  heatboard_prod_db_password:
    external: true
  heatboard_prod_pool_token:
    external: true
  heatboard_prod_session_password:
    external: true
  discord_client_secret_prod:
    external: true
  heatboard_prod_nextauth_secret:
    external: true
