services:
  app:
    image: 10.10.0.3:5000/history-server:sha-1bac615
    environment:
      - POSTGRE_HOST=db
      - POSTGRE_PORT=5432
      - POSTGRE_USER=postgres
      - POSTGRE_DB=chauffagistes
      - PORT=8050
      - GATHER_STATS=true
    command: >
      sh -c "
      export POSTGRE_PASSWORD=$$(cat /run/secrets/history_server_db_password) &&
      export STATS_API_TOKEN=$$(cat /run/secrets/history_server_stats_api_token) &&
      python main.py"
    secrets:
      - history_server_db_password
      - history_server_stats_api_token
    networks:
      - chauffagistes-net
      - traefik-public
      - history-server-internal
    deploy:
      placement:
        constraints:
          - node.labels.chauffagistes.host == docker-swarm-node02
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.history-server.rule=Host(`history.chauffagistes-btc.fr`)"
        - "traefik.http.routers.history-server.entrypoints=websecure"
        - "traefik.http.routers.history-server.tls.certresolver=letsencrypt"
        - "traefik.http.services.history-server.loadbalancer.server.port=8050"

  db:
    image: timescale/timescaledb-ha:pg17@sha256:9665079bcf1403aa1751f4139acbb5dae6b458c7653dfd357acd4e7ae0973192
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chauffagistes
      - POSTGRES_PASSWORD_FILE=/run/secrets/history_server_db_password
    secrets:
      - history_server_db_password
    networks:
      - history-server-internal
      - history-server-db-expose
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - history-server-pgdata:/home/postgres/pgdata/data
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chauffagistes"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.chauffagistes.host == hugo
      update_config:
        order: stop-first
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s

secrets:
  history_server_db_password:
    external: true
  history_server_stats_api_token:
    external: true

volumes:
  history-server-pgdata:

networks:
  chauffagistes-net:
    external: true
  traefik-public:
    external: true
  history-server-internal:
    driver: overlay
    internal: true
  history-server-db-expose:
    driver: overlay
