services:
  app:
    image: 10.10.0.3:5000/pool-site:1.1.2
    environment:
      NODE_ENV: production
      DB_USER: pool_site
      DB_NAME: pool_site
      DB_HOST: pg-ha-prod_haproxy
      HOSTNAME: "0.0.0.0"
    secrets:
      - source: pool_site_prod_db_password
        target: db_password
    networks:
      - chauffagistes-net
      - traefik-public
      - pg-prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.worload == true
      update_config:
        order: start-first
        monitor: 60s
        failure_action: rollback
      rollback_config:
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pool-site.rule=Host(`chauffagistes-btc.fr`)"
        - "traefik.http.routers.pool-site.entrypoints=websecure"
        - "traefik.http.routers.pool-site.tls.certresolver=letsencrypt"
        - "traefik.http.services.pool-site.loadbalancer.server.port=3000"

networks:
  chauffagistes-net:
    external: true
  traefik-public:
    external: true
  pg-prod:
    external: true

secrets:
  pool_site_prod_db_password:
    external: true