services:
  app:
    image: 172.16.0.3:5000/ckpool-share-exporter:sha-590e558
    environment:
      DB_NAME: ckpool
      DB_HOST: pg-ha-staging_haproxy
      DB_USER: ckpool
      BASE_LOG_DIR: /srv/ckpool/logs
      POOL_INSTANCE_NAME: "{{.Node.Hostname}}"
    command: >
      sh -c "
      export DB_PASSWORD=$$(cat /run/secrets/db_password) &&
      exec python -m ckpool_share_exporter"
    secrets:
      - source: ckpool_staging_db_password
        target: db_password
    # group_add est ignoré par `docker stack deploy` ; on passe donc par user
    user: "1000:1000" # UID/GID propriétaire des logs sur debian ; à revoir quand d'autres nœuds ckpool arrivent
    volumes:
      - type: bind
        source: /srv/ckpool/logs # symlink!
        target: /srv/ckpool/logs
        read_only: true
    networks:
      - chauffagistes-net
      - pg-staging
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.ckpool == true
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
        condition: on-failure

secrets:
  ckpool_staging_db_password:
    external: true

networks:
  chauffagistes-net:
    external: true
  pg-staging:
    external: true
