services:
  app:
    image: 10.10.0.3:5000/history-server:sha-b654d27
    environment:
      - DB_HOST=pg-ha-staging_haproxy
      - DB_USER=history_server
      - DB_NAME=history_server
      - PORT=8050
      - GATHER_STATS=true
    command: >
      sh -c "
      export DB_PASSWORD=$$(cat /run/secrets/history_server_staging_db_password) &&
      export STATS_API_TOKEN=$$(cat /run/secrets/history_server_staging_stats_api_token) &&
      exec python main.py"
    secrets:
      - history_server_staging_db_password
      - history_server_staging_stats_api_token
    networks:
      - chauffagistes-net
      - traefik-public
      - pg-staging
    deploy:
      placement:
        constraints:
          - node.labels.workload == true
      update_config:
        order: stop-first
        monitor: 60s
        failure_action: rollback
      rollback_config:
        order: stop-first
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.history-server-staging.rule=Host(`history.staging.chauffagistes-btc.fr`)"
        - "traefik.http.routers.history-server-staging.entrypoints=websecure"
        - "traefik.http.routers.history-server-staging.tls.certresolver=letsencrypt"
        - "traefik.http.services.history-server-staging.loadbalancer.server.port=8050"

secrets:
  history_server_staging_db_password:
    external: true
  history_server_staging_stats_api_token:
    external: true

networks:
  chauffagistes-net:
    external: true
  traefik-public:
    external: true
  pg-staging:
    external: true
