worker_processes 1;

events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=30s;

  server {
    listen 80;

    # coins-service staging
    location /staging/coins/ {
      rewrite ^/staging/coins/(.*) /$1 break;
      set $upstream coins-service_app:8095;
      proxy_pass http://$upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # YouTrack
    location /youtrack/ {
      rewrite ^/youtrack/(.*) /$1 break;
      set $upstream core_youtrack:8080;
      proxy_pass http://$upstream;
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
      proxy_http_version 1.1;
      proxy_set_header Upgrade    $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 300;
    }

    # Healthcheck
    location /healthz {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}