name: Reusable — Build & Push

on:
  workflow_call:
    inputs:
      service-name:
        description: "Nom du service"
        required: true
        type: string
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true

env:
  # TODO: use registry.swakraft.fr once DNS is ready
  REGISTRY: 192.168.1.201:5000

jobs:
  build-push:
    name: Build & Push
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.service-name }}
          tags: |
            type=sha,prefix=sha-,format=short
            type=ref,event=branch,prefix=branch-
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Summary
        run: |
          echo "### Image(s) publiée(s) 🐳" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY