name: Reusable — Build & Push

on:
  workflow_call:
    inputs:
      service-name:
        description: "Nom du service"
        required: true
        type: string
      build-target:
        description: "Stage Docker cible (ex: runner, migrator). Vide = image complète"
        required: false
        type: string
        default: ""
      build-args:
        required: false
        type: string
        default: ""
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true
      ORG_PAT:
        required: true

env:
  REGISTRY: 10.10.0.3:5000

jobs:
  build-push:
    name: Build & Push ${{ inputs.service-name }}${{ inputs.build-target != '' && format(' ({0})', inputs.build-target) || '' }}
    runs-on: [ self-hosted, worker ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug env
        run: |
          whoami
          echo "$PATH"
          env | sort

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.service-name }}
          tags: |
            type=sha,prefix=sha-,format=short
            type=ref,event=branch,prefix=branch-
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ${{ inputs.build-target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          secrets: |
            npmrc=//npm.pkg.github.com/:_authToken=${{ secrets.ORG_PAT }}
            pipindex=http://${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_PASSWORD }}@10.10.0.3:8081/simple/

      - name: Summary
        run: |
          echo "### Image(s) publiée(s) 🐳" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY